### types Of Analytics
#### 1. Descriptive     ->> What happend in past
#### 2. Dianostic       ->> why did it happend
#### 3. Predictive      ->>  future
#### 4. Prescriptive    ->> solution



# Numpy : Package for Multidimensional array

In [209]:
import numpy as np 

In [211]:
list_o_lists= [[1,2,3],[4,5,6],[7,8,9]]
sample_matrix = np.array(list_of_lists)
samale_matrix

NameError: name 'samale_matrix' is not defined

In [172]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [173]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [174]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [175]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [176]:
np.zeros(10 ,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [177]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [178]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [179]:
np.zeros((2,5) ,int) 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### Create an array of Zero with 2  rows and 10 columns

In [180]:
np.zeros((2,10) ,int) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [181]:
np.linspace(0,1,5)  #>>> linearly space >> equaly distribute  0 to 1  for 5 time 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [182]:
np.linspace(0,20,8)   #>>> linearly space >> equaly distribute  0 to 20 for 8 time

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [183]:
np.eye(3)   #>> generate identity  matrix [I]3*3 , digonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [184]:
np.random.rand(3,2) ##  3 row 2 coulmn (uniform distribution >> no can be in 0 to 1)

array([[0.73634391, 0.02628073],
       [0.81732989, 0.14274637],
       [0.56765733, 0.32997422]])

In [185]:
np.random.randn(3,2)   ## randn use for negative value 

array([[ 0.38054123, -1.40920494],
       [-0.36527257, -0.51213038],
       [ 0.51581905,  0.38090007]])

In [186]:
np.random.randint(33,200)  ## generate any random number bw 33 to 199

148

In [187]:
np.random.randint(0,100 , 100)  ##>> format (start , end ,  total output)

array([58, 83, 81, 54, 24, 28, 24, 94, 99, 43, 19, 46, 15, 55, 92, 73, 18,
       72, 64, 79, 10, 61, 50, 85, 50,  9,  0, 32, 43, 13, 97,  6, 89, 91,
       29, 75, 77, 20, 88, 69, 23, 65, 98, 18, 53, 89, 27, 94, 28, 35, 41,
       80, 73, 94,  2, 82,  0, 98, 41, 95, 66,  5, 54, 56, 56,  2, 88,  6,
       36,  2,  6, 94, 66, 94, 13,  5, 53, 24, 21, 38, 43, 48, 41, 36, 69,
       70, 89, 29, 21, 82, 31, 60, 20, 38, 36, 26,  1, 73, 85, 39])

In [188]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [189]:
sample_array.reshape(6, 5) ##>> format (row , coulmn)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [190]:
rand_array = np.random.randint(1,89,50)
rand_array

array([17, 43, 24, 37, 14,  7, 27, 48,  2, 38, 18, 79, 36, 37, 65, 37, 38,
       84, 62, 76,  8, 63, 36, 67,  6, 65, 63, 70, 44, 73, 47, 80, 27, 60,
       48, 36,  8, 70, 21, 13, 47, 86, 11,  7,  8, 68, 24, 84, 60, 46])

In [191]:
rand_array.min()

2

In [192]:
rand_array.max()


86

In [193]:
rand_array.argmin()  ##>>>> 


8

In [194]:
sample_array = np.arange(30)
sample_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [195]:
sample_array.dtype  ## tell about datatype

dtype('int32')

In [196]:
a = np.eye(5)   #>>> identity matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [197]:
a.T  #>>> transpose T(I) =I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [198]:
a  = np.random.rand(2,3)
a   ##>>> uniform distribution >  means range of no is 0 to 1 

array([[0.35088   , 0.02244986, 0.25652996],
       [0.91962395, 0.4857533 , 0.8614577 ]])

In [199]:
a.T

array([[0.35088   , 0.91962395],
       [0.02244986, 0.4857533 ],
       [0.25652996, 0.8614577 ]])

In [200]:
sample_array = np.arange(10,21)
print(sample_array)
type(sample_array)

[10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [201]:
sample_array[3] ##> retrive by index 

13

In [202]:
sample_array[3:7]  ##>> index will not consider 

array([13, 14, 15, 16])

In [203]:
sample_array[1:4] = 100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [204]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [205]:
subset_sample_array = sample_array[0:4]
subset_sample_array

array([ 10, 100, 100, 100])

In [206]:
subset_sample_array[1:2]  = 100
subset_sample_array

array([ 10, 100, 100, 100])

In [207]:
subset_sample_array[:]  = 100
subset_sample_array  ###>> default start and end will be there >>

array([100, 100, 100, 100])

# Two - Dimensional Array

In [125]:
import numpy as np

In [133]:
sample_matrix = np.array([[50,20,1,23],[54,23,2,22],[3,30,23,7]])
sample_matrix

array([[50, 20,  1, 23],
       [54, 23,  2, 22],
       [ 3, 30, 23,  7]])

In [134]:
sample_matrix[2][3]  ##>>> means find the element in row[2] coulmn[3] = that is 7

7

In [135]:
sample_matrix[2,:]   ## >>2nd row and 2coulam full


array([ 3, 30, 23,  7])

In [136]:
sample_matrix[2] ## same ->> 2nd row and 2coulam full

array([ 3, 30, 23,  7])

In [138]:
sample_matrix[:,(3,2)]  ##>> : sense 

array([[23,  1],
       [22,  2],
       [ 7, 23]])

In [147]:
sample_matrix[(0,1),(2,2)]

array([1, 2])

In [148]:
sample_array  = np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [149]:
sample_array +sample_array 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [150]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [151]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [152]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [153]:
np.max(sample_array)

19

In [154]:
np.min(sample_array)

1

In [155]:
np.argmax(sample_array)

18

In [156]:
np.argmin(sample_array)

0

In [157]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [158]:
np.std(sample_array)  #>>> standerd eviation

5.477225575051661

In [159]:
np.var(sample_array)  #>>>> varience

30.0

In [160]:
np.mean(sample_array)   #>>> mean (madhya)


10.0

In [161]:
array = np.random.randn(3,4)
array

array([[-1.69793288, -0.98482883, -0.37907722, -1.63080774],
       [ 0.51759656,  1.34293625,  0.31414643,  0.97356725],
       [-0.74485247,  0.65242814, -0.75235503,  0.98408355]])

In [163]:
np.round(array , decimals = 3)

array([[-1.698, -0.985, -0.379, -1.631],
       [ 0.518,  1.343,  0.314,  0.974],
       [-0.745,  0.652, -0.752,  0.984]])

In [169]:
sports = np.array (['golf','cricket','cricket','hockey','football','chess','basketball'])
print(sports)
np.unique(sports)

['golf' 'cricket' 'cricket' 'hockey' 'football' 'chess' 'basketball']


array(['basketball', 'chess', 'cricket', 'football', 'golf', 'hockey'],
      dtype='<U10')